[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#1E88E5"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E2638"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false
